version: '3.7'
services:
  ai_services:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ~/.cloudmesh:/root/.cloudmesh
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '8000:8000'
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yanwan
      MONGO_INITDB_ROOT_PASSWORD: <user-password>
      MONGO_INITDB_DATABASE: cloudmesh
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro